### PR TITLE
Rename CMSO dataset 1

### PR DESCRIPTION
**Pull request by sbesson**
Following Essen discussion, this changes the prefix of the CMSO curated datasets from `cmso` to `cmsodataset`

### CODE REVIEW

**Comment by pcmasuzzo** [comment]
Good for me!

**Comment by agbeltran** [comment]
Good for me too! Merging as it was agreed in the Essen meeting.

**Comment by simleo** [comment]
I'm a bit late to the party but I'd still like to leave a few notes for future reference:

* I understand not wanting to clash with ontology terms and such, but in the long term `cmsodataset` might be a bit too verbose
* `dataset` might suggest the presence of image data while it’s all metadata instead (this also applies to the repo name)

**Comment by sbesson** [comment]
@simleo understood. `cmsodataset` was chosen as it matches the current name of this repository but we could review it if creates confusion. Do you have an alternate suggestion?

**Comment by simleo** [comment]
Perhaps `cmsomd`, where `md` stands for metadata? Although I would give another chance to `cmso` if the risk of ID clashes is not too high. An ontology term should look like `CMSO:0001`, right? That should be easily distinguishable from `cmso0001`.

Again, sorry for chiming in late but I was attending the MULTIMOT meeting while this was being merged :)

**Pull request merged**
