### PR TITLE
Add travis checks

### PR DESCRIPTION
**Pull request by simleo**
Adds a script that checks all ISA datasets and a Travis config file to run it automatically.

To test: enable Travis for the main repo and check that the build is green.

### CODE REVIEW

**Comment by agbeltran** [comment]
This is great!

**Comment by simleo** [comment]
I'm afraid we're not datapackage spec compliant yet, see https://github.com/CellMigStandOrg/biotracks/issues/3. In particular, the data package we have now leads to:

```
Failed validating u'pattern' in schema[u'properties'][u'resources'][u'items'][u'properties'][u'name']:
    {u'description': u"An identifier for this package. Lower case characters with '.', '_' and '-' are allowed.",
     u'pattern': u'^([a-z0-9._-])+$',
     u'title': u'Name',
     u'type': u'string'}

On instance[u'resources'][0][u'name']:
    u'objectsTable'
```

**Comment by simleo** [comment]
Actually, this is due to the fact that this datapackage has been written before https://github.com/CellMigStandOrg/biotracks/pull/15

**Comment by simleo** [comment]
I've fixed the data package to make it specs compliant and added the check

**Comment by sbesson** [comment]
:+1: LGTM. I wonder whether this will not turn into a single `validate.py` scripts with various options (`validate.py --isa-only`) but we can review the architecture when necessary. In the meantime, having some minimal validation of the format containers on every Pull Request adding a new dataset is really an important feature.

**Pull request merged**
