### PR TITLE
Add more comprehensive checking of ISA-Tab using ISA API

### PR DESCRIPTION
**Pull request by djcomlab**
Build on using the `isatools.isatab` package for attempting to load datasets with `isatab.load()`, and then validate datasets with `isatab.validate()`.

### CODE REVIEW

**Comment by agbeltran** [comment]
Thank you @djcomlab - I was working on this and have pushed some code to my fork but had not sent the PR yet. 

@simleo @pcmasuzzo I will make sure the checks pass for this and then we can review it.

Thanks

**Comment by simleo** [comment]
@djcomlab please fix flake8 errors:

```
./check_isa.py:3:1: F401 'json' imported but unused
./check_isa.py:10:80: E501 line too long (88 > 79 characters)
./check_isa.py:10:89: W291 trailing whitespace
./check_isa.py:11:80: E501 line too long (89 > 79 characters)
./check_isa.py:11:90: W291 trailing whitespace
./check_isa.py:12:17: W291 trailing whitespace
./check_isa.py:17:80: E501 line too long (83 > 79 characters)
./check_isa.py:19:80: E501 line too long (92 > 79 characters)
./check_isa.py:22:80: E501 line too long (81 > 79 characters)
./check_isa.py:23:80: E501 line too long (81 > 79 characters)
./check_isa.py:31:80: E501 line too long (89 > 79 characters)
./check_isa.py:35:1: W293 blank line contains whitespace
./check_isa.py:36:80: E501 line too long (86 > 79 characters)
./check_isa.py:42:80: E501 line too long (83 > 79 characters)
./check_isa.py:45:80: E501 line too long (90 > 79 characters)
./check_isa.py:46:80: E501 line too long (91 > 79 characters)
./check_isa.py:47:50: W291 trailing whitespace
./check_isa.py:49:80: E501 line too long (90 > 79 characters)
```

**Comment by simleo** [comment]
The check is failing because the script expects to find `i_investigation.txt` while the actual file has a capital `I`. Is this allowed by the ISA specs? This dataset was copied from `https://github.com/ISA-tools/ISAdatasets/tree/tests/tab/MIACME-Cellmissy1`.

**Comment by proccaserra** [comment]
@simleo, I am surprised about the error you are reporting. there are several tests in the ISA-API where the reader or the validator get files starting with i_ but no requirement is made on the string following the prefix. Can you provide more detail about the error you are getting  and which methods are being invoked ?

**Comment by djcomlab** [comment]
There's another possible bug actually in the ISA API using these datasets, where the loader picks up the Investigation Identifier as a string OK in the first test dataset, but as a float in the second, which is unexpected.

**Comment by simleo** [comment]
```
$ python3 check_isa.py 
/usr/local/lib/python3.5/dist-packages/isatools/isatab.py:3: FutureWarning: The pandas.parser module is deprecated and will be removed in a future version. Please import from the pandas.io.parser instead
  from pandas.parser import CParserError
attempting to load cmsodataset0001-masuzzo/isa
loaded 3 study sources
loaded 12 study samples
cmsodataset0001-masuzzo/isa load OK
attempting to load cmsodataset0002-masuzzo/isa
loaded 1 study sources
loaded 60 study samples
Traceback (most recent call last):
  File "check_isa.py", line 62, in <module>
    main()
  File "check_isa.py", line 30, in main
    assert num_study_sources == 3
AssertionError
```

**Pull request merged**
